// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wbfbhdmkawoxpxkeeucj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndiZmJoZG1rYXdveHB4a2VldWNqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2MjY1MTksImV4cCI6MjA3MzIwMjUxOX0.kGpL1zMD78aoZ091dJzvD-M3f5Xmnqzf6AOOJphzY1Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});